config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    confirmations: 'confirmations'
  }

  root 'users#index'
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show create] do
      resources :comments, only: %i[new create]
    end
  end
  get 'new', to: 'posts#new'  
  put '/post/:id/like', to: 'likes#create', as: 'like'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  validates :text, presence: true, length: { maximum: 100 }

  after_save :update_comment_counter

  private

  def update_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :post

  after_commit :update_likes_counter

  private

  def update_likes_counter
    post.increment!(:likes_counter)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :comments
  has_many :likes

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_save :update_post_count

  def returns_five_most_recent_comments
    comments.order(created_at: :DESC).limit(5)
  end

  private

  def update_post_count
    author.update(post_counter: author.posts.count)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, foreign_key: 'author_id'
  has_many :comments, foreign_key: 'author_id'
  has_many :likes, foreign_key: 'author_id'

  before_save :counter

  # validates :name, presence: true
  # validates :post_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  def return_recent_post
    posts.limit(3)
  end

  def counter
    self.post_counter = 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @post = Post.find(params[:post_id])
    @comment = Comment.new((params.require(:comment).permit(:text)))
    @comment.post = @post
    @comment.author = current_user
    flash[:notice] = if @comment.save
                       'Comment created'
                     else
                       'Comment not created'
                     end
    redirect_to user_post_path(@user, @post)
  end
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
  private

  def after_confirmation_path_for(_resource_name, resource)
    sign_in(resource)
    root_path
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    user = User.find(params[:user_id])
    post = user.posts.find(params[:id])
    Like.create(author_id: current_user.id, post_id: post.id)
    if Like.exists?(author_id: current_user.id)
      flash[:notice] = 'Post liked'
    else
      flash[:error] = 'Post cannot be like'
    end
    redirect_to user_post_path(user, post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
  end

  def new
    @user = current_user
  end

  def create
    @post = current_user.posts.new(params.require(:post).permit(:title, :text))
    @post.comments_counter = 0
    @post.likes_counter = 0
    flash[:notice] = if @post.save
                       'Post created'
                     else
                       'Post not created'
                     end
    redirect_to user_post_path(current_user, @post)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.return_recent_post
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogAppRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if user_signed_in?%>
      <%= link_to 'Sign Out', "/users/sign_out", method: :delete %>
      <%= link_to 'Edit Account', "/users/edit" %>
    <% else %>
      <%= link_to 'Sign In', "/users/sign_in" %>
    <% end %>
    
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="user_profile">
    <div class="photo_container">
        <%= image_tag 'user-avatar.png',
            alt: 'user',
            class: 'photo' %>
    </div>
    <div class="info_container">        
        <p class="name_container"><%= @user.name%></p>  
        <p class="posts_counter">Numer of posts: <%= @user.post_counter %></p>           
    </div>    
</div>
<div class="bio_cnt">
    <h2 class="bio_title">Bio</h2>
    <p><%= @user.bio%></p>
</div>
<ul class="posts_container">
<% @posts.includes([:comments]).each do |post| %> 
    <%= link_to :action => 'show', :id => post.id do %>
        <li class="post_list">
            <h2 class="bio_title"><%= post.title %></h2>
            <p><%= post.text %></p>
            <div class="counter_container">
                <p>Comments: <%= post.comments_counter %></p>
                <p>Likes: <%= post.likes_counter %></p>
            </div>
            <div class="comments_container">
                <ul> 
                <h2 class="bio_title">Comments: </h2>
                    <% post.returns_five_most_recent_comments.each do |c| %>
                    <li><p><%= c.text %></p></li>
                     <% end %>
                </ul>
            </div>         
        </li>
    <% end %>         
<% end %> 
</ul>
<%= button_to "Go back", user_path(@user.id), :method => :get, class:"button" %>

app/views/posts/new.html.erb
<div class="form_cnt show_form">
<h2>Create a new Post</h2>
<%= form_with model: [@user, @user.posts.build] do |form| %>
  <%= form.text_field :title, placeholder: 'Title', require: true %>
  <%= form.text_field :text, placeholder: 'Text', require: true  %>
  <%= form.submit %>  
<% end %>
</div>

app/views/posts/show.html.erb
<ul class="posts_container">
    <li class="post_list">
        <div class="post_show_info">
            <h2 ><%= @post.title %></h2>
            <p class="post_author">Post by: <%= @user.name%></p> 
        </div> 
        <p><%= @post.text %></p>
        <div class="counter_container">            
            <p>Comments: <%= @post.comments_counter %></p>
            <p>Likes: <%= @post.likes_counter %></p>
        </div>                
    </li> 
    <%= button_to 'Like', like_path(user_id: @user.id, post_id: @post.id), method: "put", class: 'like_btn button' %>
    <div class="comments_container">
        <ul>
            <h2 class="bio_title">Comments: </h2>
            <% @post.comments.all.each do |c| %>
                <li><p><%= c.text %></p></li>
            <% end %>
        </ul>
    </div>
    <div class="form_cnt">
        <h2>Add a comment: </h2>
        <%= form_with model: [@user, @post, @post.comments.build] do |form| %>            
            <%= form.text_field :text %>
            <%= form.submit %>
        <% end %>
        <% flash.each do |type, msg| %>
            <% if type == 'notice' %>
                <div class="notice">
                <%= msg %>
                </div>
            <% end %>
            <% if type == 'error' %>
                <div class="notice">
                <%= msg %>
                </div>
            <% end %>
         <% end %>
    </div>
</ul>

app/views/users/index.html.erb
<ul class="user_container">
    <% @users.each do |u| %>    
      <%= link_to :action => 'show', :id => u.id do %>
        <li class="user_list">
          <div class="photo_container">
            <%= image_tag 'user-avatar.png',
            alt: 'user',
            class: 'photo' %>
          </div>      
          <div class="info_container">        
            <p class="name_container"><%= u.name %></p>
            <p class="posts_counter">Numer of posts: <%= u.post_counter %></p>
          </div>
        </li>    
      <% end %>
    <% end %>
</ul>

app/views/users/show.html.erb
<div class="user_profile">
    <div class="photo_container">
        <%= image_tag 'user-avatar.png',
            alt: 'user',
            class: 'photo' %>
    </div>
    <div class="info_container">        
        <p class="name_container"><%= @user.name%></p>
        <p class="posts_counter">Numer of posts: <%= @user.post_counter %></p>             
    </div>    
</div>
<div class="bio_cnt">
    <h2 class="bio_title">Bio</h2>
    <p><%= @user.bio%></p>
</div>
<ul class="posts_container">
<% @posts.each do |post| %> 
    <li class="post_list">
        <p class="post_tile"><%= post.title %></p>
        <p><%= post.text %></p>
        <div class="counter_container">
            <p>Comments: <%= post.comments_counter %></p>
            <p>Likes: <%= post.likes_counter %></p>
        </div>
    </li>    
<% end %>
</ul>
 <%= button_to "Show all posts", user_posts_path(@user.id), :method => :get, class:"button" %>
